R snippet callbacks
facultyai/dash-bootstrap-components pull request #616
Opened 2021-07-01 14:09 UTC by AnnMarieW

2021-07-01 17:07 UTC, tcbegley commented
Thanks @AnnMarieW!

Does this supersede #596?

2021-07-03 09:56 UTC, tcbegley requested changes
Thanks @AnnMarieW!

I have left some comments, I believe with the suggested changes all tests should pass reliably 🤞

2021-07-03 09:56 UTC, tcbegley commented on docs/components_page/components/__tests__/test_toast.py
> +    runner.find_element(".close").click()
This is a weird one, but it looks like for some reason if the close button is clicked too early here the Julia test fails. Can you add

```diff
+ time.sleep(2)
runner.find_element(".close").click()
```

then the tests should pass

2021-07-03 09:56 UTC, tcbegley commented on docs/components_page/components/__tests__/test_collapse.py
> +
Similarly to toast example, can you add a `time.sleep(2)` here, I think it helps make the test a bit more robust.

2021-07-03 09:56 UTC, tcbegley commented on docs/components_page/components/__tests__/test_collapse.py
> +
Ditto

2021-07-03 18:04 UTC, AnnMarieW commented on docs/components_page/components/__tests__/test_collapse.py
> +        (HERE.parent / "collapse" / "accordion.jl"), "collapses"
:facepalm:

2021-07-03 18:06 UTC, AnnMarieW commented
I incorporated all your suggestions with the latest commit :bowing_woman:

2021-07-21 17:17 UTC, merged