Add inner container to navbar examples
facultyai/dash-bootstrap-components pull request #667
Opened 2021-08-31 18:59 UTC by glsdown

Updated navbar examples per #651 to include the inner container.

2021-08-31 21:09 UTC, tcbegley requested changes

2021-08-31 21:09 UTC, tcbegley commented on docs/components_page/components/navbar.md
>  Here is an example of a custom navbar, see the `examples/` folder in the [GitHub repo](https://github.com/facultyai/dash-bootstrap-components/blob/main/examples/python/advanced-component-usage/navbar
TODO: opening the collapse on small screens causes formatting issue, needs to be looked into.

2021-09-01 21:21 UTC, glsdown commented
Probably worth also including in here the fix for the examples including the Navs on the home page of the docs

2021-09-03 08:03 UTC, tcbegley approved these changes

2021-09-03 08:03 UTC, merged